11/01/2021 11:51:14 AM Started
11/01/2021 11:51:14 AM Finished
11/01/2021 11:51:28 AM Received signal to terminate bot and event loop.
11/01/2021 11:51:28 AM Cleaning up tasks.
11/01/2021 11:51:28 AM Cleaning up after 1 tasks.
11/01/2021 11:51:28 AM All tasks finished cancelling.
11/01/2021 11:51:28 AM Closing the event loop.
11/01/2021 11:51:42 AM Started
11/01/2021 11:51:42 AM Finished
11/01/2021 11:53:34 AM Received signal to terminate bot and event loop.
11/01/2021 11:53:34 AM Cleaning up tasks.
11/01/2021 11:53:34 AM Cleaning up after 1 tasks.
11/01/2021 11:53:34 AM All tasks finished cancelling.
11/01/2021 11:53:34 AM Closing the event loop.
11/01/2021 11:54:00 AM Started
11/01/2021 11:54:00 AM Finished
11/01/2021 11:56:45 AM Started
11/01/2021 11:56:45 AM Finished
11/01/2021 12:44:35 PM Started
11/01/2021 12:44:35 PM Finished
11/01/2021 12:46:31 PM Started
11/01/2021 12:46:31 PM Finished
11/01/2021 12:48:40 PM Task was destroyed but it is pending!
task: <Task pending name='discord.py: on_message' coro=<Client._run_event() done, defined at C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py:349> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000017B8297B7F0>()]>>
11/01/2021 12:49:54 PM Started
11/01/2021 12:49:54 PM Finished
11/01/2021 12:50:45 PM Task was destroyed but it is pending!
task: <Task pending name='discord.py: on_message' coro=<Client._run_event() running at C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py:351> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002836F126EB0>()]>>
11/01/2021 12:50:45 PM Task was destroyed but it is pending!
task: <Task pending name='discord.py: on_message' coro=<Client._run_event() running at C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py:351> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002836FF03B80>()]>>
11/01/2021 12:52:24 PM Can't keep up, shard ID None websocket is 18.6s behind.
11/01/2021 12:59:57 PM Started
11/01/2021 12:59:57 PM Finished
11/01/2021 01:01:19 PM Task was destroyed but it is pending!
task: <Task pending name='discord.py: on_message' coro=<Client._run_event() done, defined at C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py:349> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002158396C7C0>()]>>
11/01/2021 01:08:32 PM Started
11/01/2021 01:08:32 PM Finished
11/01/2021 01:09:16 PM Received signal to terminate bot and event loop.
11/01/2021 01:09:16 PM Cleaning up tasks.
11/01/2021 01:09:16 PM Cleaning up after 1 tasks.
11/01/2021 01:09:16 PM All tasks finished cancelling.
11/01/2021 01:09:16 PM Closing the event loop.
11/01/2021 01:09:30 PM Started
11/01/2021 01:09:30 PM Finished
11/01/2021 01:13:19 PM Can't keep up, shard ID None websocket is 17.7s behind.
11/01/2021 01:20:45 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:20:55 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:21:05 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:21:15 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 49, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 418, in _open_connection
    self._socket.open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 574, in open_connection
    self.sock.connect(sockaddr)

11/01/2021 01:21:17 PM Websocket closed with 1000, cannot reconnect.
11/01/2021 01:21:17 PM Attempting a reconnect in 0.35s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 512, in connect
    await self.ws.poll_event()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 585, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
11/01/2021 01:21:18 PM Shard ID None has sent the RESUME payload.
11/01/2021 01:21:18 PM Shard ID None has successfully RESUMED session 9e34a182a791eadb9f599f74776d7875 under trace ["gateway-prd-main-vcl5",{"micros":1052,"calls":["discord-sessions-blue-prd-2-82",{"micros":44}]}].
11/01/2021 01:31:11 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:31:21 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:31:31 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:31:41 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:31:51 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:32:01 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 230, in _do_auth
    self._auth_switch_request(username, password)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 246, in _auth_switch_request
    packet = self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:32:11 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 41, in on_message
    cursor.execute(f'UPDATE xp_count SET xp = (xp+{xp_new}) WHERE user = {author.id}')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:32:18 PM Timed out receiving packet. Attempting a reconnect.
11/01/2021 01:32:18 PM Got a request to RESUME the websocket.
11/01/2021 01:32:18 PM Shard ID None has sent the RESUME payload.
11/01/2021 01:32:41 PM Shard ID None has successfully RESUMED session 9e34a182a791eadb9f599f74776d7875 under trace ["gateway-prd-main-mfw1",{"micros":1762,"calls":["discord-sessions-blue-prd-2-82",{"micros":85}]}].
11/01/2021 01:33:09 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:33:20 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:33:30 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:33:40 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:33:50 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 146, in on_member_join
    cnx.commit()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1229, in commit
    self._execute_query("COMMIT")
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1248, in _execute_query
    self.cmd_query(query)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/01/2021 01:33:55 PM Timed out receiving packet. Attempting a reconnect.
11/01/2021 01:33:55 PM Got a request to RESUME the websocket.
11/01/2021 01:33:55 PM Shard ID None has sent the RESUME payload.
11/01/2021 01:34:08 PM Shard ID None has successfully RESUMED session 9e34a182a791eadb9f599f74776d7875 under trace ["gateway-prd-main-2fk1",{"micros":1111,"calls":["discord-sessions-blue-prd-2-82",{"micros":48}]}].
11/01/2021 03:04:18 PM Started
11/01/2021 03:04:18 PM Finished
11/01/2021 03:05:17 PM Can't keep up, shard ID None websocket is 13.3s behind.
11/01/2021 03:07:26 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 241, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 230, in _do_auth
    self._auth_switch_request(username, password)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 246, in _auth_switch_request
    packet = self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:10:25 PM Started
11/03/2021 09:10:25 PM Finished
11/03/2021 09:11:12 PM Started
11/03/2021 09:11:12 PM Finished
11/03/2021 09:12:20 PM Received signal to terminate bot and event loop.
11/03/2021 09:12:20 PM Cleaning up tasks.
11/03/2021 09:12:20 PM Cleaning up after 1 tasks.
11/03/2021 09:12:20 PM All tasks finished cancelling.
11/03/2021 09:12:20 PM Closing the event loop.
11/03/2021 09:12:33 PM Started
11/03/2021 09:12:33 PM Finished
11/03/2021 09:21:54 PM Timed out receiving packet. Attempting a reconnect.
11/03/2021 09:21:54 PM Got a request to RESUME the websocket.
11/03/2021 09:21:54 PM Attempting a reconnect in 1.28s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:21:55 PM Attempting a reconnect in 2.98s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:21:58 PM Attempting a reconnect in 4.57s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:22:02 PM Attempting a reconnect in 1.48s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:22:04 PM Attempting a reconnect in 18.90s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:22:23 PM Attempting a reconnect in 32.11s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 509, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 308, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 1902, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
11/03/2021 09:22:55 PM Shard ID None has sent the RESUME payload.
11/03/2021 09:22:56 PM Shard ID None session has been invalidated.
11/03/2021 09:22:56 PM Got a request to IDENTIFY the websocket.
11/03/2021 09:23:01 PM Shard ID None has sent the IDENTIFY payload.
11/03/2021 09:23:02 PM Shard ID None has connected to Gateway: ["gateway-prd-main-n33d",{"micros":95962,"calls":["discord-sessions-green-prd-2-40",{"micros":95172,"calls":["start_session",{"micros":90750,"calls":["api-prd-main-z6jf",{"micros":81261,"calls":["get_user",{"micros":6932},"add_authorized_ip",{"micros":2697},"get_guilds",{"micros":13337},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":3699,"calls":[]}]}]}] (Session ID: 8789fa8c59a5bfa55d4d97db3058e189).
11/03/2021 09:23:04 PM Started
11/03/2021 09:23:04 PM Finished
11/03/2021 09:25:02 PM Started
11/03/2021 09:25:02 PM Finished
11/03/2021 09:51:59 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:09 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:19 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:29 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:39 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:49 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:52:59 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:53:09 PM Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:53:19 PM Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:53:29 PM Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 230, in _do_auth
    self._auth_switch_request(username, password)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 246, in _auth_switch_request
    packet = self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 09:53:37 PM Websocket closed with 1000, cannot reconnect.
11/03/2021 09:53:37 PM Attempting a reconnect in 0.61s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 512, in connect
    await self.ws.poll_event()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 585, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
11/03/2021 09:53:38 PM Shard ID None has sent the RESUME payload.
11/03/2021 09:53:39 PM Shard ID None session has been invalidated.
11/03/2021 09:53:39 PM Got a request to IDENTIFY the websocket.
11/03/2021 09:53:44 PM Shard ID None has sent the IDENTIFY payload.
11/03/2021 09:53:45 PM Shard ID None has connected to Gateway: ["gateway-prd-main-djhr",{"micros":79259,"calls":["discord-sessions-green-prd-2-168",{"micros":76224,"calls":["start_session",{"micros":30993,"calls":["api-prd-main-vvp8",{"micros":27483,"calls":["get_user",{"micros":2987},"add_authorized_ip",{"micros":2505},"get_guilds",{"micros":3781},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":5176,"calls":[]}]}]}] (Session ID: 326860c474116be785926630079b01ba).
11/03/2021 09:53:47 PM Started
11/03/2021 09:53:47 PM Finished
11/03/2021 10:05:31 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:05:41 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:05:51 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:06:01 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:06:11 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 212, in _do_auth
    self._socket.switch_to_ssl(ssl_options.get('ca'),
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 458, in switch_to_ssl
    self.sock = context.wrap_socket(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()

11/03/2021 10:06:21 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1013, in connect
    self._post_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 985, in _post_connection
    self.set_charset_collation(self._charset_id)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 943, in set_charset_collation
    self._execute_query("SET NAMES '{0}' COLLATE '{1}'".format(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1248, in _execute_query
    self.cmd_query(query)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:06:24 PM Timed out receiving packet. Attempting a reconnect.
11/03/2021 10:06:24 PM Got a request to RESUME the websocket.
11/03/2021 10:06:24 PM Shard ID None has sent the RESUME payload.
11/03/2021 10:07:00 PM Shard ID None has successfully RESUMED session 326860c474116be785926630079b01ba under trace ["gateway-prd-main-zfxx",{"micros":1746,"calls":["discord-sessions-green-prd-2-168",{"micros":106}]}].
11/03/2021 10:07:15 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:07:25 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:07:35 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:07:45 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:07:55 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:05 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:15 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:26 PM Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:36 PM Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:46 PM Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:08:56 PM Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:09:06 PM Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 18, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 230, in _do_auth
    self._auth_switch_request(username, password)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 246, in _auth_switch_request
    packet = self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:09:16 PM Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 42, in on_message
    cnx.commit()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1229, in commit
    self._execute_query("COMMIT")
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1248, in _execute_query
    self.cmd_query(query)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:09:22 PM Timed out receiving packet. Attempting a reconnect.
11/03/2021 10:09:22 PM Got a request to RESUME the websocket.
11/03/2021 10:09:23 PM Shard ID None has sent the RESUME payload.
11/03/2021 10:09:23 PM Shard ID None session has been invalidated.
11/03/2021 10:11:27 PM Got a request to IDENTIFY the websocket.
11/03/2021 10:11:33 PM Shard ID None has sent the IDENTIFY payload.
11/03/2021 10:11:33 PM Shard ID None has connected to Gateway: ["gateway-prd-main-9526",{"micros":128574,"calls":["discord-sessions-green-prd-2-143",{"micros":127527,"calls":["start_session",{"micros":106663,"calls":["api-prd-main-cpt5",{"micros":98711,"calls":["get_user",{"micros":5024},"add_authorized_ip",{"micros":11553},"get_guilds",{"micros":15492},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":13060,"calls":[]}]}]}] (Session ID: 4cf284c8531e8d213fd5ccfd3c08a317).
11/03/2021 10:11:35 PM Started
11/03/2021 10:11:35 PM Finished
11/03/2021 10:33:42 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:33:52 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:34:02 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:34:12 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 131, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:34:22 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\main.py", line 137, in on_member_join
    cursor.execute(f'SELECT * FROM invitecodes WHERE invite_code = \'{inv.code}\'')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:34:32 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 42, in on_message
    cnx.commit()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1229, in commit
    self._execute_query("COMMIT")
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1248, in _execute_query
    self.cmd_query(query)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 846, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 501, in _send_cmd
    return self._socket.recv()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
    return self.read(buflen)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
    return self._sslobj.read(len)

11/03/2021 10:34:42 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "d:\Aman\All-Bots\MTB\main.py", line 242, in <module>
    bot.run('ODgzMjMyOTcwNDE1MTUzMTcz.YTG8zQ.CoVQrRswbBi1VCjNlJ5gygiIVcM')
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 653, in run
    loop.run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "d:\Aman\All-Bots\MTB\cogs\xp_counter.py", line 49, in on_message
    cnx.reconnect(attempts=1, delay=0)
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 1121, in reconnect
    self.connect()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1009, in connect
    self._open_connection()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 420, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 212, in _do_auth
    self._socket.switch_to_ssl(ssl_options.get('ca'),
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 458, in switch_to_ssl
    self.sock = context.wrap_socket(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()

11/03/2021 10:34:48 PM Websocket closed with 1000, cannot reconnect.
11/03/2021 10:34:48 PM Attempting a reconnect in 0.06s
Traceback (most recent call last):
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 512, in connect
    await self.ws.poll_event()
  File "C:\Users\anchal\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 585, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
11/03/2021 10:34:48 PM Shard ID None has sent the RESUME payload.
11/03/2021 10:34:58 PM Shard ID None has successfully RESUMED session 4cf284c8531e8d213fd5ccfd3c08a317 under trace ["gateway-prd-main-rhrd",{"micros":894,"calls":["discord-sessions-green-prd-2-143",{"micros":71}]}].
11/04/2021 12:52:21 PM Started
11/04/2021 12:52:21 PM Finished
